name: Update Image

on:
  workflow_dispatch:
  repository_dispatch:
    types: [from-m1schedule]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Image
        run: |
          curl -o image.jpg ${{ github.event.client_payload.url }}

      - name: Push Changes
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Updated image"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push One Signal
        run: |
          sleep 30
          curl --request POST \
                --url https://onesignal.com/api/v1/notifications \
                --header 'Authorization: Basic ${{ env.API_KEY }}' \
                --header 'accept: application/json' \
                --header 'content-type: application/json' \
                --data '
          {
                "included_segments": [
                  "Subscribed Users",
                  "Active Users",
                  "Inactive Users"
                ],
                "contents": {
                  "en": "時間割が更新されました。",
                  "ja": "時間割が更新されました。"
                },
                "name": "mito1daily",
                "app_id": "${{ env.APP_ID }}"
          }
          '
        env:
          API_KEY: ${{ secrets.API_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
